---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pudim
  labels:
    k8s-app: pudim
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: pudim
  template:
    metadata:
      labels:
        k8s-app: pudim
        name: pudim
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: msfidelis/pudim:v0
        name: pudim
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: "256m"
            memory: "512m"
---
kind: Service
apiVersion: v1
metadata:
  name: pudim
spec:
  selector:
    k8s-app: pudim
  ports:
    - protocol: TCP
      port: 80
      name: web
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: pudim.raj.ninja
    http:
      paths:
      - path: /
        backend:
          serviceName: pudim
          servicePort: 80

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: pudim
spec:
  maxReplicas: 5
  minReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pudim